trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@2
  inputs:
    version: '16.x'

- script: |
    npm install
    npm run build
  displayName: 'Instalar dependencias y construir aplicación'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Service Connection'
    appName: 'app-prueba-tecnica'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Desplegar en Azure App Service'